src/Entity/Homepage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HomepageRepository")
 */
class Homepage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $locale;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $limit_highlights;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sidebar_about_me_photo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $sidebar_about_me_text;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $sidebar_categories = [];

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="update")
     */
    private $modified;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sidebar_about_me_url_facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sidebar_about_me_url_instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sidebar_about_me_url_github;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sidebar_about_me_url_youtube;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sidebar_about_me_url_linkedin;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $sidebar_about_me_active = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getLimitHighlights(): ?int
    {
        return $this->limit_highlights;
    }

    public function setLimitHighlights(?int $limit_highlights): self
    {
        $this->limit_highlights = $limit_highlights;

        return $this;
    }

    public function getSidebarAboutMePhoto(): ?string
    {
        return $this->sidebar_about_me_photo;
    }

    public function setSidebarAboutMePhoto(?string $sidebar_about_me_photo): self
    {
        $this->sidebar_about_me_photo = $sidebar_about_me_photo;

        return $this;
    }

    public function getSidebarAboutMeText(): ?string
    {
        return $this->sidebar_about_me_text;
    }

    public function setSidebarAboutMeText(?string $sidebar_about_me_text): self
    {
        $this->sidebar_about_me_text = $sidebar_about_me_text;

        return $this;
    }

    public function getSidebarCategories(): ?array
    {
        return $this->sidebar_categories;
    }

    public function setSidebarCategories(?array $sidebar_categories): self
    {
        $this->sidebar_categories = $sidebar_categories;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(?\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    public function getSidebarAboutMeUrlFacebook(): ?string
    {
        return $this->sidebar_about_me_url_facebook;
    }

    public function setSidebarAboutMeUrlFacebook(?string $sidebar_about_me_url_facebook): self
    {
        $this->sidebar_about_me_url_facebook = $sidebar_about_me_url_facebook;

        return $this;
    }

    public function getSidebarAboutMeUrlInstagram(): ?string
    {
        return $this->sidebar_about_me_url_instagram;
    }

    public function setSidebarAboutMeUrlInstagram(?string $sidebar_about_me_url_instagram): self
    {
        $this->sidebar_about_me_url_instagram = $sidebar_about_me_url_instagram;

        return $this;
    }

    public function getSidebarAboutMeUrlGithub(): ?string
    {
        return $this->sidebar_about_me_url_github;
    }

    public function setSidebarAboutMeUrlGithub(?string $sidebar_about_me_url_github): self
    {
        $this->sidebar_about_me_url_github = $sidebar_about_me_url_github;

        return $this;
    }

    public function getSidebarAboutMeUrlYoutube(): ?string
    {
        return $this->sidebar_about_me_url_youtube;
    }

    public function setSidebarAboutMeUrlYoutube(?string $sidebar_about_me_url_youtube): self
    {
        $this->sidebar_about_me_url_youtube = $sidebar_about_me_url_youtube;

        return $this;
    }

    public function getSidebarAboutMeUrlLinkedin(): ?string
    {
        return $this->sidebar_about_me_url_linkedin;
    }

    public function setSidebarAboutMeUrlLinkedin(?string $sidebar_about_me_url_linkedin): self
    {
        $this->sidebar_about_me_url_linkedin = $sidebar_about_me_url_linkedin;

        return $this;
    }

    public function getSidebarAboutMeActive(): ?bool
    {
        return $this->sidebar_about_me_active;
    }

    public function setSidebarAboutMeActive(?bool $sidebar_about_me_active): self
    {
        $this->sidebar_about_me_active = $sidebar_about_me_active;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $text;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $url_photo;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category")
     */
    private $categories;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $active = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Template")
     * @ORM\JoinColumn(nullable=false)
     */
    private $template;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MediaPostRel", mappedBy="post")
     */
    private $mediaPostRel;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $locale;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $header_image;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $highlight = false;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->mediaPostRel = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(?\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    public function getDeleted(): ?\DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?\DateTimeInterface $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(?string $url_photo): self
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPublished(): ?\DateTimeInterface
    {
        return $this->published;
    }

    public function setPublished(?\DateTimeInterface $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): self
    {
        $this->template = $template;

        return $this;
    }

    /**
     * @return Collection|MediaPostRel[]
     */
    public function getMediaPostRel(): Collection
    {
        return $this->mediaPostRel;
    }

    public function addMediaPostRel(MediaPostRel $mediaPostRel): self
    {
        if (!$this->mediaPostRel->contains($mediaPostRel)) {
            $this->mediaPostRel[] = $mediaPostRel;
            $mediaPostRel->setPost($this);
        }

        return $this;
    }

    public function removeMediaPostRel(MediaPostRel $mediaPostRel): self
    {
        if ($this->mediaPostRel->contains($mediaPostRel)) {
            $this->mediaPostRel->removeElement($mediaPostRel);
            // set the owning side to null (unless already changed)
            if ($mediaPostRel->getPost() === $this) {
                $mediaPostRel->setPost(null);
            }
        }

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getHeaderImage(): ?string
    {
        return $this->header_image;
    }

    public function setHeaderImage(?string $header_image): self
    {
        $this->header_image = $header_image;

        return $this;
    }

    public function getHighlight(): ?bool
    {
        return $this->highlight;
    }

    public function setHighlight(?bool $highlight): self
    {
        $this->highlight = $highlight;

        return $this;
    }
}

templates/pages/about-me.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {# TODO: Implemented this page. #}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1 property="title">
                    About me
                </h1>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1>
                    Entre em contato
                </h1>
            </div>
        </div>
    </div>
    {# TODO #}
{% endblock %}

templates/pages/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ name_site }}
{% endblock %}

{# This macro is for display the big highlight card. #}
{% macro highlightBigCard(highlight, addClass, imageFormat) %}
    <a href="{{ path('post_detail', {slug: highlight.slug}) }}"
       class="homepage-highlights-card{{ addClass }} js-highlights-item">
        {% if highlight.urlPhoto is not empty %}
            <img alt="{{ highlight.title|default() }}"
                 class="lazy"
                 data-src="{{ asset(highlight.urlPhoto)|imagine_filter(imageFormat) }}"/>
        {% endif %}

        <div class="homepage-highlights-content">
            {% if highlight.title is not empty %}
                <h2 class="homepage-highlights-title">
                    {{ highlight.title }}
                </h2>
            {% endif %}
        </div>
    </a>
{% endmacro %}

{% block body %}
    {% include 'includes/header.html.twig' %}

    {% set addClassHighlight = ' mb-5' %}
    {% set classHighlightBig = ' col-7' %}
    {% set formatHighlightBig = '998x848' %}

    {% if 1 == highlights|length %}
        {% set classHighlightBig = classHighlightBig ~ ' col-12' %}
        {% set addClassHighlight = addClassHighlight ~ ' homepage-highlight--one' %}
        {% set formatHighlightBig = '1710x788' %}
    {% elseif 2 == highlights|length %}
        {% set classHighlightBig = classHighlightBig ~ ' col-6' %}
        {% set addClassHighlight = addClassHighlight ~ ' homepage-highlight--two' %}
    {% endif %}

    <div class="container mt-5 homepage">
        {% if highlights[0] is defined %}
            <div id="{{ register_component('homepage-highlights') }}" class="row{{ addClassHighlight }}">
                <div class="col homepage-highlights-desktop">
                    <div class="row">
                        {{ _self.highlightBigCard(highlights[0], classHighlightBig, formatHighlightBig) }}

                        {% if highlights[2] is defined %}
                            <div class="col-5">
                                <div class="row mx-0 pb-4">
                                    <a href="{{ path('post_detail', {slug: highlights[1].slug}) }}"
                                       class="col homepage-highlights-card homepage-highlights-card--small js-highlights-item">
                                        {% if highlights[1].urlPhoto is not empty %}
                                            <img alt="{{ highlights[1].title|default() }}"
                                                 class="lazy"
                                                 data-src="{{ asset(highlights[1].urlPhoto)|imagine_filter('675x405') }}"/>
                                        {% endif %}

                                        <div class="homepage-highlights-content">
                                            {% if highlights[1].title is not empty %}
                                                <h2 class="homepage-highlights-title">
                                                    {{ highlights[1].title }}
                                                </h2>
                                            {% endif %}
                                        </div>
                                    </a>
                                </div>

                                <div class="row mx-0">
                                    <a href="{{ path('post_detail', {slug: highlights[2].slug}) }}"
                                       class="col homepage-highlights-card homepage-highlights-card--small js-highlights-item">
                                        {% if highlights[2].urlPhoto is not empty %}
                                            <img alt="{{ highlights[2].title|default() }}"
                                                 class="lazy"
                                                 data-src="{{ asset(highlights[2].urlPhoto)|imagine_filter('675x405') }}"/>
                                        {% endif %}

                                        <div class="homepage-highlights-content">
                                            {% if highlights[2].title is not empty %}
                                                <h2 class="homepage-highlights-title">
                                                    {{ highlights[2].title }}
                                                </h2>
                                            {% endif %}
                                        </div>
                                    </a>
                                </div>
                            </div>
                        {% elseif highlights[1] is defined %}
                            {{ _self.highlightBigCard(highlights[1], classHighlightBig, formatHighlightBig) }}
                        {% endif %}
                    </div>
                </div>

                <div class="homepage-highlights-mobile">
                    <div class="js-homepage-highlights-slider">
                        {% for highlight in highlights %}
                            <a href="{{ path('post_detail', {slug: highlight.slug}) }}"
                               class="homepage-highlights-slide js-homepage-highlights-slide">
                                <img alt="{{ highlight.title|default() }}"
                                     class="lazy"
                                     data-src="{{ asset(highlight.urlPhoto)|imagine_filter('675x405') }}"/>

                                <h2 class="homepage-highlights-slide-title">
                                    {{ highlight.title }}
                                </h2>
                            </a>
                        {% endfor %}
                    </div>

                    <div class="homepage-highlights-slider-dots js-homepage-highlights-slider-dots">
                        {# Initialize via JS. #}
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="row homepage-content">
            <div class="homepage-main col-md-8 col-sm-12 px-0">
                {% for post in posts %}
                    <div class="homepage-posts-card">
                        <div class="homepage-posts-card-link-limited">
                            <a href="{{ path('post_detail', {slug: post.slug}) }}"
                               class="stretched-link"></a>

                            <div class="media">
                               {% if post.image is not empty %}
                                    <div class="homepage-posts-card-img-wrapper mr-4">
                                        <img src="{{ asset(post.image)|imagine_filter('600x375') }}"
                                             class="homepage-posts-card-img rounded img-fluid"
                                             alt="{{ post.title }}">
                                    </div>
                                {% endif %}

                                <div class="media-body">
                                    <h5 id="{{ register_component('dotdotdot') }}"
                                        class="homepage-posts-card-title">
                                        {{ post.title }}
                                    </h5>

                                    <div id="{{ register_component('dotdotdot') }}"
                                         class="homepage-posts-card-text font-weight-light">
                                        {{ post.description }}
                                    </div>

                                    <div class="media homepage-posts-card-user">
                                        <img src="{{ asset(post.userAvatar)|imagine_filter('40x40') }}"
                                             class="rounded-circle mr-3"
                                             alt="{{ post.userName }}">

                                        <div class="media-body author-body">
                                            <h6 class="mt-0 mb-1 font-weight-normal">
                                                {{ post.userName }}
                                            </h6>

                                            {% include 'includes/published.html.twig' with {published: post.published} only %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="homepage-sidebar col-md-4 col-sm-12">
                {% if homepage.sidebarAboutMeActive %}
                    <div class="mb-4">
                        <h4 class="text-center mb-4">
                            {{ 'app.general.about_me'|trans }}
                        </h4>

                        {% if homepage.sidebarAboutMePhoto is not empty %}
                            <div class="homepage-about-me-img-wrapper">
                                <img src="{{ asset(homepage.sidebarAboutMePhoto)|imagine_filter('600x600') }}"
                                     class="homepage-about-me-img rounded-circle img-fluid mb-4"
                                     alt="">
                            </div>
                        {% endif %}

                        {% if homepage.sidebarAboutMeText is not empty %}
                            <div class="homepage-about-me-text mb-3">
                                {{ homepage.sidebarAboutMeText }}
                            </div>
                        {% endif %}

                        <ul class="list-inline text-center">
                            {% if homepage.sidebarAboutMeUrlFacebook is not empty %}
                                <li class="list-inline-item">
                                    <a href="{{ homepage.sidebarAboutMeUrlFacebook }}" target="_blank">
                                        <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}

                            {% if homepage.sidebarAboutMeUrlInstagram is not empty %}
                                <li class="list-inline-item">
                                    <a href="{{ homepage.sidebarAboutMeUrlInstagram }}" target="_blank">
                                        <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}

                            {% if homepage.sidebarAboutMeUrlYoutube is not empty %}
                                <li class="list-inline-item">
                                    <a href="{{ homepage.sidebarAboutMeUrlYoutube }}" target="_blank">
                                        <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}

                            {% if homepage.sidebarAboutMeUrlLinkedin is not empty %}
                                <li class="list-inline-item">
                                    <a href="{{ homepage.sidebarAboutMeUrlLinkedin }}" target="_blank">
                                        <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}

                            {% if homepage.sidebarAboutMeUrlGithub is not empty %}
                                <li class="list-inline-item">
                                    <a href="{{ homepage.sidebarAboutMeUrlGithub }}" target="_blank">
                                        <span class="fa-stack fa-lg">
                                          <i class="fa fa-circle fa-stack-2x"></i>
                                          <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/register.html.twig
{% extends 'simple.html.twig' %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                {{ form_start(form) }}

                {{ form_widget(form) }}

                <input type="submit" value="Add"/>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}