src/Entity/Setting.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SettingRepository")
 */
class Setting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $google_gtag_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_github;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $app_id_facebook;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $show_comments_facebook = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGoogleGtagId(): ?string
    {
        return $this->google_gtag_id;
    }

    public function setGoogleGtagId(?string $google_gtag_id): self
    {
        $this->google_gtag_id = $google_gtag_id;

        return $this;
    }

    public function getUrlFacebook(): ?string
    {
        return $this->url_facebook;
    }

    public function setUrlFacebook(?string $url_facebook): self
    {
        $this->url_facebook = $url_facebook;

        return $this;
    }

    public function getUrlInstagram(): ?string
    {
        return $this->url_instagram;
    }

    public function setUrlInstagram(string $url_instagram): self
    {
        $this->url_instagram = $url_instagram;

        return $this;
    }

    public function getUrlLinkedin(): ?string
    {
        return $this->url_linkedin;
    }

    public function setUrlLinkedin(?string $url_linkedin): self
    {
        $this->url_linkedin = $url_linkedin;

        return $this;
    }

    public function getUrlGithub(): ?string
    {
        return $this->url_github;
    }

    public function setUrlGithub(?string $url_github): self
    {
        $this->url_github = $url_github;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getAppIdFacebook(): ?string
    {
        return $this->app_id_facebook;
    }

    public function setAppIdFacebook(?string $app_id_facebook): self
    {
        $this->app_id_facebook = $app_id_facebook;

        return $this;
    }

    public function getShowCommentsFacebook(): ?bool
    {
        return $this->show_comments_facebook;
    }

    public function setShowCommentsFacebook(?bool $show_comments_facebook): self
    {
        $this->show_comments_facebook = $show_comments_facebook;

        return $this;
    }
}

templates/includes/column-right.html.twig
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">Sobre mim</h5>
		<img src="{{ asset('images/thomaskanzig-2.jpg') }}" alt="..." class="img-fluid rounded-circle photo-profile">
    <p class="card-text mt-3">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="card-link">Read more</a>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">Social links</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">Mais lidos</h5>
  </div>
</div>

templates/includes/comments-facebook.html.twig
{% if setting().showCommentsFacebook %}
  <div class="fb-comments"
       data-href="{{ base_url ~ '' ~ app.request.requestUri }}"
       data-width="100%"
       data-numposts="20">
  </div>
{% endif %}

templates/includes/footer.html.twig
<!-- Footer -->

<hr>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">

          {% if setting().urlInstagram is defined and setting().urlInstagram is not empty %}
            <li class="list-inline-item">
              <a href="{{ setting().urlInstagram}}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          {% if setting().urlFacebook is defined and setting().urlFacebook is not empty %}
            <li class="list-inline-item">
              <a href="{{ setting().urlFacebook }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          {% if setting().urlLinkedin is defined and setting().urlLinkedin is not empty %}
            <li class="list-inline-item">
              <a href="{{ setting().urlLinkedin }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}

          {% if setting().urlGithub is defined and setting().urlGithub is not empty %}
            <li class="list-inline-item">
              <a href="{{ setting().urlGithub }}" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          {% endif %}
        </ul>
        <p class="copyright text-muted">Copyright &copy; Thomas Kanzig 2019</p>
      </div>
    </div>
  </div>
</footer>

templates/includes/header.html.twig
{% set headingClass = 'page-heading' %}
{% set mainClass = '' %}

{% if 'gallery' == type|default() %}
    {% set headingClass = 'post-heading' %}
{% endif %}

{% if 'pages_homepage' == app.request.attributes.get("_route") %}
    {% set mainClass = ' d-none d-md-block' %}
{% endif %}

<header class="masthead{{ mainClass }}">
    <div class="masthead-image-wrapper">
        <img id="{{ register_component('parallax') }}"
             data-src="{{ asset(image|default('images/bg-index.jpg')|imagine_filter('1440x800')) }}"
             alt=""
             class="lazy"/>
    </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="{{ headingClass }}">
          <h1>{{ title|default('Blog Personal') }}</h1>
          <!--Uma descricao basica da pagina
          <span class="subheading">Uma descricao basica da pagina</span-->
        </div>
      </div>
    </div>
  </div>
</header>

templates/includes/meta-icons.html.twig
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('/images/favicon/apple-touch-icon.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('/images/favicon/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('/images/favicon/favicon-16x16.png') }}">
<link rel="manifest" href="{{ asset('/images/favicon/site.webmanifest') }}">
<link rel="mask-icon" href="{{ asset('/images/favicon/safari-pinned-tab.svg') }}" color="#ffffff">
<meta name="theme-color" content="#ffffff">

templates/includes/meta.html.twig
{%- spaceless %}
    {% set metaPublisher = 'Thomas Kanzig' %}
    {% set metaSiteName = name_site %}
    {% set metaLocaleParts = app.request.locale|split('_') %}
    {% set metaLanguage = metaLocaleParts[0] %}
    {% set metaCountry = metaLocaleParts[1]|default(null) %}
    {% set metaLocale = metaLocaleParts|length == 1 ? metaLanguage : metaLanguage ~ '_' ~ metaCountry|upper %}
    {% set metaUrl = app.request.uri %}

    {# Get meta title. #}
    {% set metaTitle = metaTitle|default(metaSiteName) %}

    {# Get meta description. #}
    {% set metaDescription = metaDescription|default('') %}
    {% if metaDescription|trim %}
        {% set metaDescription = metaDescription|length > 320 ? metaDescription|slice(0, 316) ~ ' ...' : metaDescription %}
    {% endif %}

    {# Get meta image. #}
    {% set metaImage = asset(metaImage|default('/images/thomas-kanzig.jpg'))|imagine_filter('640x420') %}

    {% set metaBotTags = {
        'revisit-after': '2 days',
    } %}

    {% set metaDefaultTags = {
        'language': metaLanguage,
        'publisher': metaPublisher,
        'author': metaSiteName,
        'copyright': metaSiteName,
        'audience': 'all',
        'distribution': 'global',
        'image': metaImage,
    } %}

    {% set metaDCTags = {
        'DC.Title': metaTitle,
        'DC.Publisher': metaPublisher,
        'DC.Copyright': metaSiteName,
    } %}

    {% set metaTwitterTags = {
        'twitter:card': 'summary',
        'twitter:url': metaUrl,
        'twitter:title': metaTitle,
        'twitter:description': metaDescription,
        'twitter:image': metaImage,
    } %}

    {% set ogMetaTags = {
        'og:site_name': metaSiteName,
        'og:url': metaUrl,
        'og:title': metaTitle,
        'og:image': metaImage,
        'og:type': 'website',
        'og:description': metaDescription,
        'og:locale': metaLocale
    } %}
{% endspaceless -%}

{% block title %}
        <title>{{ metaTitle }}</title>
{%- endblock -%}

{%- block description -%}
    {%- if metaDescription -%}
        <meta name="description" content="{{ metaDescription }}"/>
    {%- endif -%}
{%- endblock -%}

{# Meta Bot Tags #}
{% block metaBotTags %}
    {% for property, value in metaBotTags if value %}
        <meta name="{{ property }}" content="{{ value }}"/>
    {% endfor %}
{% endblock %}

{# Meta Default Tags #}
{% block metaDefaultTags %}
    {% for property, value in metaDefaultTags if value %}
        <meta name="{{ property }}" content="{{ value }}"/>
    {% endfor %}
{% endblock %}

{# Meta DC Tags #}
{% block metaDCTags %}
    {% for property, value in metaDCTags if value %}
        <meta name="{{ property }}" content="{{ value }}"/>
    {% endfor %}
{% endblock %}

{# Meta Twitter Tags #}
{% block metaTwitterTags %}
    {% for property, value in metaTwitterTags if value %}
        <meta name="{{ property }}" content="{{ value }}"/>
    {% endfor %}
{% endblock %}

{# Meta OG Tags #}
{% block ogMetaTags %}
    {% for property, value in ogMetaTags if value %}
        <meta property="{{ property }}" content="{{ value }}"/>
    {% endfor %}
{% endblock %}

{# Google gtag #}
{% if setting().googleGtagId is defined and setting().googleGtagId is not empty %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ setting().googleGtagId }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '{{ setting().googleGtagId }}');
    </script>
{%- endif -%}

templates/includes/navigation.html.twig
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ path('pages_homepage') }}">{{ name_site }}</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{{ path('post_index') }}">Blog</a>
        </li>

        {% if 1 < locales|split(',')|length %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
               href="#"
               id="navbarDropdown"
               role="button"
               data-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false">
              {{ app.request.locale }}
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-locale"
                 aria-labelledby="navbarDropdown">
              {% for locale in locales|split(',') if locale != app.request.locale %}
                <a class="dropdown-item dropdown-item-locale"
                   href="{{ path('pages_homepage.' ~ locale, { _locale: locale }) }}">
                  {{ locale }}
                </a>
              {% endfor %}
            </div>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/published.html.twig
{% set showIconDate = false %}
{% set showTime = true %}
{% set addClass = '' %}

{% if options is defined  %}
    {% if options.showIconDate is defined %}
        {% set showIconDate = options.showIconDate %}
    {% endif %}

    {% if options.showTime is defined %}
        {% set showTime = options.showTime %}
    {% endif %}

    {% if options.addClass is defined %}
        {% set addClass = ' ' ~ options.addClass %}
    {% endif %}
{% endif %}

{% if published is not empty %}
    <div class="published{{ addClass }}">
        {% if showIconDate %}
            <i class="fa fa-calendar gallery-photos-img-data-published-icon" aria-hidden="true"></i>
        {% else %}
                {{ 'app.general.published_in'|trans }}
        {% endif %}

        {{ published|date("M j, Y") }}

        {% if showTime %}
            <span class="published-time">
              {{ published|date("g:i a") }}
            </span>
        {% endif %}
    </div>
{% endif %}

templates/includes/see-more-posts.html.twig
{% if posts %}
  <div class="show-more-posts pt-5">
    <div class="container">
      <h5 class="show-more-posts-title font-weight-bolder mb-4 pb-3">
        {{ 'app.general.see_more'|trans }}
      </h5>

      <div class="row">
        {% for post in posts %}
          <div class="col-md-4 col-lg-4 mb-5">
            <div class="card">
              <div class="card-stretched-link-limited">
                <a href="{{ path('post_detail', {slug: post.slug}) }}"
                   class="stretched-link"></a>

                {% if post.image is not empty %}
                  <div class="card-img-wrapper">
                    <img src="{{ asset(post.image)|imagine_filter('600x375') }}"
                         class="card-img-top"
                         alt="{{ post.title }}">
                  </div>
                {% endif %}

                <div class="card-body px-0">
                  <h4 class="card-title my-0">
                    {{ post.title }}
                  </h4>
                </div>
              </div>

              <div class="media">
                <img src="{{ asset(post.userAvatar)|imagine_filter('40x40') }}"
                     class="rounded-circle mr-3"
                     alt="{{ post.userName }}">

                <div class="media-body author-body">
                  <h6 class="mt-0 mb-1 font-weight-normal">
                    {{ post.userName }}
                  </h6>

                  {% include 'includes/published.html.twig' with {published: post.published} only %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}

templates/includes/show-more-posts.html.twig
{% if posts %}
  <div class="show-more-content pt-5">
    <div class="container">
      <h5 class="show-more-content-title font-weight-bolder mb-4 pb-3">
        {{ 'app.general.see_more'|trans }}
      </h5>

      <div class="row">
        {% for post in posts %}
          <div class="col-md-4 col-lg-4 mb-5">
            <div class="card">
              <div class="card-stretched-link-limited">
                <a href="{{ path('post_detail', {slug: post.slug}) }}" class="stretched-link"></a>

                {% if post.image is not empty %}
                  <div class="card-img-wrapper">
                    <img src="{{ asset(post.image)|imagine_filter('600x375') }}"
                         class="card-img-top"
                         alt="{{ post.title }}">
                  </div>
                {% endif %}

                <div class="card-body px-0">
                  <h4 class="card-title my-0">
                    {{ post.title }}
                  </h4>
                </div>
              </div>

              <div class="media">
                <img src="{{ asset(post.userAvatar)|imagine_filter('40x40') }}"
                     class="rounded-circle mr-3"
                     alt="{{ post.userName }}">

                <div class="media-body author-body">
                  <h6 class="mt-0 mb-1 font-weight-normal">
                    {{ post.userName }}
                  </h6>

                  <div class="d-flex">
                    <small class="text-black-50 author-post-created">
                      {{ post.created|date("M n, Y") }}
                    </small>

                    <small class="text-black-50 author-post-created author-post-time">
                      {{ post.created|date("h:i a") }}
                    </small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}