src/Entity/Setting.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SettingRepository")
 */
class Setting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $google_gtag_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_github;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $app_id_facebook;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $show_comments_facebook = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGoogleGtagId(): ?string
    {
        return $this->google_gtag_id;
    }

    public function setGoogleGtagId(?string $google_gtag_id): self
    {
        $this->google_gtag_id = $google_gtag_id;

        return $this;
    }

    public function getUrlFacebook(): ?string
    {
        return $this->url_facebook;
    }

    public function setUrlFacebook(?string $url_facebook): self
    {
        $this->url_facebook = $url_facebook;

        return $this;
    }

    public function getUrlInstagram(): ?string
    {
        return $this->url_instagram;
    }

    public function setUrlInstagram(string $url_instagram): self
    {
        $this->url_instagram = $url_instagram;

        return $this;
    }

    public function getUrlLinkedin(): ?string
    {
        return $this->url_linkedin;
    }

    public function setUrlLinkedin(?string $url_linkedin): self
    {
        $this->url_linkedin = $url_linkedin;

        return $this;
    }

    public function getUrlGithub(): ?string
    {
        return $this->url_github;
    }

    public function setUrlGithub(?string $url_github): self
    {
        $this->url_github = $url_github;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getAppIdFacebook(): ?string
    {
        return $this->app_id_facebook;
    }

    public function setAppIdFacebook(?string $app_id_facebook): self
    {
        $this->app_id_facebook = $app_id_facebook;

        return $this;
    }

    public function getShowCommentsFacebook(): ?bool
    {
        return $this->show_comments_facebook;
    }

    public function setShowCommentsFacebook(?bool $show_comments_facebook): self
    {
        $this->show_comments_facebook = $show_comments_facebook;

        return $this;
    }
}

templates/admin.html.twig
{% set route_name = app.request.attributes.get('_route') %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %} {{ name_admin }} {% endblock %}</title>
        {% block stylesheets %}
            {# 'app' must match the first argument to addEntry() in webpack.config.js #}
            {{ encore_entry_link_tags('admin') }}

            <!-- Renders a link tag (if your module requires any CSS)
                 <link rel="stylesheet" href="/build/app.css"> -->
        {% endblock %}
    </head>
    <body class="hold-transition skin-blue sidebar-mini fixed">
        <div class="wrapper">
            {# Detect if was added more navbar header links from the body block. #}
            {% set _headerNavbar = block('headerNavbar') is defined ? block('headerNavbar'):'' %}

            {% include 'includes/admin/header.html.twig' with {headerNavbar: _headerNavbar} %}

            {% include 'includes/admin/sidebar-left.html.twig' %}

            <div class="content-wrapper">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}

                {% block body %}{% endblock %}
            </div>

            {% include 'includes/admin/footer.html.twig' %}

            {% include 'includes/admin/sidebar-right.html.twig' %}
        </div>
        <!-- ./wrapper -->

        {% block javascripts %}
            {{ encore_entry_script_tags('admin') }}
            <!--Renders website.js & a webpack runtime.js file
                <script src="/build/runtime.js"></script>
                <script src="/build/website.js"></script> -->
            <script>
                web.startComponents({{ get_components() }});
            </script>
        {% endblock %}

        {% block scripts %}
            <!-- Add more javascript. -->
        {% endblock %}
    </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {%- block meta -%}
            {%- include "includes/meta.html.twig" %}
        {% endblock %}

        {%- block metaIcons -%}
            {%- include "includes/meta-icons.html.twig" %}
        {% endblock %}

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
        {% block stylesheets %}
            {# 'website' must match the first argument to addEntry() in webpack.config.js #}
            {{ encore_entry_link_tags('website') }}

            <!-- Renders a link tag (if your module requires any CSS)
                 <link rel="stylesheet" href="/build/app.css"> -->
        {% endblock %}
    </head>
    <body>
        {% if setting().appIdFacebook is defined and setting().appIdFacebook is not empty %}
            {# Facebook Javascript SDK #}
            <div id="fb-root"></div>
            <script async defer crossorigin="anonymous"
                    src="https://connect.facebook.net/{{ countries_locales[app.request.locale] }}/sdk.js#xfbml=1&version=v5.0&appId={{ setting().appIdFacebook }}&autoLogAppEvents=1">
            </script>
        {% endif %}

        {% include 'includes/navigation.html.twig' %}

        {% block body %}{% endblock %}

        {% include 'includes/footer.html.twig' %}

        {% block javascripts %}
            {{ encore_entry_script_tags('website') }}

            <!-- Renders website.js & a webpack runtime.js file
                <script src="/build/runtime.js"></script>
                <script src="/build/website.js"></script> -->

            <script> web.startComponents({{ get_components() }}); </script>
        {% endblock %}

        {% block scripts %}
            <!-- Add more javascript. -->
        {% endblock %}
    </body>
</html>

templates/simple.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %}Simple Page{% endblock %}</title>
        {% block stylesheets %} {% endblock %}
    </head>
    <body>

        {% block body %} {% endblock %}
        {% block javascripts %} {% endblock %}
    </body>
</html>

templates/sitemap.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    {% for url in urls %}
        <url>
            <loc>{{ url.loc }}</loc>

            {% if url.lastmod is defined %}
                <lastmod>{{ url.lastmod }}</lastmod>
            {% endif %}

            {% if url.changefreq is defined %}
                <changefreq >{{ url.changefreq }}</changefreq>
            {% endif %}

            {% if url.priority is defined %}
                <priority>{{ url.priority }}</priority>
            {% endif %}

        </url>
    {% endfor %}
</urlset>