src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $text;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $url_photo;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category")
     */
    private $categories;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $active = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Template")
     * @ORM\JoinColumn(nullable=false)
     */
    private $template;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MediaPostRel", mappedBy="post")
     */
    private $mediaPostRel;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $locale;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $header_image;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $highlight = false;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->mediaPostRel = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(?\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    public function getDeleted(): ?\DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?\DateTimeInterface $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(?string $url_photo): self
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPublished(): ?\DateTimeInterface
    {
        return $this->published;
    }

    public function setPublished(?\DateTimeInterface $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): self
    {
        $this->template = $template;

        return $this;
    }

    /**
     * @return Collection|MediaPostRel[]
     */
    public function getMediaPostRel(): Collection
    {
        return $this->mediaPostRel;
    }

    public function addMediaPostRel(MediaPostRel $mediaPostRel): self
    {
        if (!$this->mediaPostRel->contains($mediaPostRel)) {
            $this->mediaPostRel[] = $mediaPostRel;
            $mediaPostRel->setPost($this);
        }

        return $this;
    }

    public function removeMediaPostRel(MediaPostRel $mediaPostRel): self
    {
        if ($this->mediaPostRel->contains($mediaPostRel)) {
            $this->mediaPostRel->removeElement($mediaPostRel);
            // set the owning side to null (unless already changed)
            if ($mediaPostRel->getPost() === $this) {
                $mediaPostRel->setPost(null);
            }
        }

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getHeaderImage(): ?string
    {
        return $this->header_image;
    }

    public function setHeaderImage(?string $header_image): self
    {
        $this->header_image = $header_image;

        return $this;
    }

    public function getHighlight(): ?bool
    {
        return $this->highlight;
    }

    public function setHighlight(?bool $highlight): self
    {
        $this->highlight = $highlight;

        return $this;
    }
}

src/Entity/Setting.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SettingRepository")
 */
class Setting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $google_gtag_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_github;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $app_id_facebook;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0})
     */
    private $show_comments_facebook = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGoogleGtagId(): ?string
    {
        return $this->google_gtag_id;
    }

    public function setGoogleGtagId(?string $google_gtag_id): self
    {
        $this->google_gtag_id = $google_gtag_id;

        return $this;
    }

    public function getUrlFacebook(): ?string
    {
        return $this->url_facebook;
    }

    public function setUrlFacebook(?string $url_facebook): self
    {
        $this->url_facebook = $url_facebook;

        return $this;
    }

    public function getUrlInstagram(): ?string
    {
        return $this->url_instagram;
    }

    public function setUrlInstagram(string $url_instagram): self
    {
        $this->url_instagram = $url_instagram;

        return $this;
    }

    public function getUrlLinkedin(): ?string
    {
        return $this->url_linkedin;
    }

    public function setUrlLinkedin(?string $url_linkedin): self
    {
        $this->url_linkedin = $url_linkedin;

        return $this;
    }

    public function getUrlGithub(): ?string
    {
        return $this->url_github;
    }

    public function setUrlGithub(?string $url_github): self
    {
        $this->url_github = $url_github;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getAppIdFacebook(): ?string
    {
        return $this->app_id_facebook;
    }

    public function setAppIdFacebook(?string $app_id_facebook): self
    {
        $this->app_id_facebook = $app_id_facebook;

        return $this;
    }

    public function getShowCommentsFacebook(): ?bool
    {
        return $this->show_comments_facebook;
    }

    public function setShowCommentsFacebook(?bool $show_comments_facebook): self
    {
        $this->show_comments_facebook = $show_comments_facebook;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields="email", message="This email is already used")
 * @UniqueEntity(fields="username", message="This username is already used")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min=5,max=200)
     */
    private $fullname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min=5,max=200)
     */
    private $username;

    /**
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Please inform an email.")
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $url_avatar;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getDeleted(): ?\DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?\DateTimeInterface $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {

    }

    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->email,
            $this->password
        ]);
    }

    public function unserialize($serialized)
    {
        list($this->id,
            $this->username,
            $this->email,
            $this->password) = unserialize($serialized);
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getUrlAvatar(): ?string
    {
        return $this->url_avatar;
    }

    public function setUrlAvatar(?string $url_avatar): self
    {
        $this->url_avatar = $url_avatar;

        return $this;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Repository\PostRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PostController extends AbstractController
{
    public function index(PostRepository $repository, Request $request, PaginatorInterface $paginator)
    {

        $q = $request->query->get('q'); /* get text search */
        $queryBuilder = $repository->getWithSearchQueryBuilder($q, [
            'active' => true
        ]);

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/* page number */,
            10 /* limit per page */
        );

        // Get globals variables from twig.
        $twigGlobals = $this->get('twig')->getGlobals();

        return $this->render('post/index.html.twig', [
            'posts' => $pagination,
            'metaTitle' => 'Blog - '.$twigGlobals['name_site'],
        ]);
    }

    public function detail($slug)
    {
        /** @var Post $post */
        $post = $this->getDoctrine()
            ->getRepository(Post::class)
            ->findOneBy(['slug' => $slug]);

        if (!$post) {
            throw $this->createNotFoundException(
                'Post not found'
            );
        }

        return $this->render($post->getTemplate()->getView(), [
            'post' => $post,
            'metaTitle' => $post->getTitle(),
            'metaDescription' => $post->getDescription(),
            'metaImage' => $post->getUrlPhoto(),
        ]);
    }
}

templates/post/blog.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'includes/header.html.twig' %}

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 mx-auto">
                <article class="blog-detail">
                    <header>
                        {% if post.title is not empty %}
                            <h1 class="blog-detail-title">{{ post.title }}</h1>
                        {% endif %}
                        <div class="media author mb-4">
                            {% if post.user.urlAvatar is not empty %}
                                <img src="{{ asset(post.user.urlAvatar)|imagine_filter('100x100') }}"
                                     class="mr-3 author-photo rounded-circle"
                                     alt="{{ post.user.fullname }}">
                            {% endif %}

                            <div class="media-body">
                                <h5 class="mt-2 mb-1 author-fullname">{{ post.user.fullname }}</h5>

                                {% include 'includes/published.html.twig' with {published: post.published} only %}
                            </div>
                        </div>
                    </header>

                    <div class="text ckeditor">
                        {% if post.text is not empty %}
                            {{ post.text|raw }}
                        {% endif %}
                    </div>

                    {% include 'includes/comments-facebook.html.twig' %}
                </article>
            </div>
        </div>
    </div>

    {% include 'includes/see-more-posts.html.twig' with {posts: posts} only %}
{% endblock %}

{% block scripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

templates/post/gallery.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'includes/header.html.twig' with {
        image: post.headerImage,
        title: post.title,
        type: 'gallery',
    } only %}

    {% set showFBComments = setting().showCommentsFacebook %}

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 mx-auto">
                <article class="gallery-detail">
                    <header>
                        <div class="media author mb-4">
                            {% if post.user.urlAvatar is not empty %}
                                <img src="{{ asset(post.user.urlAvatar)|imagine_filter('100x100') }}"
                                     class="mr-3 author-photo rounded-circle"
                                     alt="{{ post.user.fullname }}">
                            {% endif %}

                            <div class="media-body">
                                <h5 class="mt-2 mb-1 author-fullname">{{ post.user.fullname }}</h5>

                                {% include 'includes/published.html.twig' with {
                                    published: post.published
                                } only %}
                            </div>
                        </div>
                    </header>

                    <div class="text">
                        {% if post.text is not empty %}
                            {{ post.text|raw }}
                        {% endif %}
                    </div>
                </article>
            </div>
        </div>
    </div>

    {% if 0 < post.mediaPostRel.count %}
        {# Gallery preview photos list. #}
        <div class="container-fluid">
            <div id="{{ register_component('gallery', {showFBComments: showFBComments }) }}" class="gallery-photos col-lg-10 mx-auto">
                <div class="js-gallery-photos-inner row">
                    {% for mediaPost in post.mediaPostRel|reverse %}
                        {% set size = gallerySize(loop.index) %}
                        {% set imageData = mediaData[mediaPost.media.id]|default() %}

                        <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 gallery-item js-gallery-photo-item">
                            <div class="gallery-photos-img-wrapper">
                                <a href="#"
                                   data-toggle="modal"
                                   data-target=".gallery-modal"
                                   data-position="{{ loop.index }}"
                                   data-id="{{ mediaPost.media.id }}"
                                   data-url="{{ asset(mediaPost.media.file)|imagine_filter('gallery_post_full') }}"
                                   data-title="{{ imageData.title|default(post.title) }}"
                                   data-description="{{ imageData.description|default() }}"
                                   data-published="{{ mediaPost.media.created|date('Y-m-d H:i:s') }}"
                                   data-author-name="{{ mediaPost.media.user.fullname }}"
                                   data-author-avatar="{{ asset(mediaPost.media.user.urlAvatar|default('images/avatar.png'))|imagine_filter('100x100') }}"
                                   class="js-gallery-photo-data">

                                    <img src="{{ asset(mediaPost.media.file)|imagine_filter(size) }}"
                                         alt="{{ imageData.title|default(post.title) }}"
                                         class="img-fluid gallery-photos-img">
                                </a>

                                <div class="gallery-photos-img-data">
                                    {% if imageData and imageData.title is not empty %}
                                        <h3 class="gallery-photos-img-data-title js-gallery-photos-img-data-title">
                                            {{ imageData.title }}
                                        </h3>
                                    {% endif %}

                                    {% include 'includes/published.html.twig' with {
                                        published: mediaPost.media.created,
                                        options: {
                                            showIconDate: true,
                                            showTime: false,
                                            addClass: 'gallery-photos-img-data-published'
                                        }
                                    } only %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                {# Gallery modal. #}
                <div class="modal fade gallery-modal js-gallery-modal"
                     tabindex="-1"
                     role="dialog"
                     aria-labelledby="exampleModalLongTitle"
                     aria-hidden="true">

                    <button type="button" class="close gallery-modal-close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="gallery-modal-main-arrow-toggler js-gallery-modal-main-arrow-toggler">
                                    <i class="fa" aria-hidden="true"></i>
                                </div>

                                <div class="modal-main js-gallery-modal-main">
                                    <img src="" class="gallery-modal-img js-gallery-modal-img" alt="">

                                    <div class="gallery-modal-nav-prev js-gallery-modal-nav-prev">
                                        <i class="fa fa-chevron-left" aria-hidden="true"></i>
                                    </div>

                                    <div class="gallery-modal-nav-next js-gallery-modal-nav-next">
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </div>
                                </div>

                                <div class="modal-right js-gallery-modal-right">
                                    <div class="modal-right-inner js-gallery-modal-right-inner">
                                        <div class="media mb-3">
                                            <img class="mr-3 rounded-circle gallery-modal-author-avatar js-gallery-modal-author-avatar"
                                                 src=""
                                                 alt="">
                                            <div class="media-body">
                                                <h5 class="mt-1 mb-1 gallery-modal-author-name js-gallery-modal-author-name">
                                                    {# Initialized via JS. #}
                                                </h5>

                                                <div class="gallery-modal-published js-gallery-modal-published">
                                                    {# Initialized via JS. #}
                                                </div>
                                            </div>
                                        </div>

                                        <h4 class="gallery-modal-title js-gallery-modal-title">
                                            {# Initialized via JS. #}
                                        </h4>

                                        <div class="gallery-modal-description js-gallery-modal-description">
                                            {# Initialized via JS. #}
                                        </div>

                                        <div class="gallery-modal-fb-comments js-gallery-modal-fb-comments">
                                            {# Initialized via JS. #}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="gallery-modal-paging js-gallery-modal-paging">
                        <span class="pr-1 js-gallery-modal-paging-current">
                            {# Initialized via JS. #}
                        </span>
                            {{ 'app.general.of'|trans }}
                            <span class="px-1 js-gallery-modal-paging-total">
                            {# Initialized via JS. #}
                        </span>
                            {{ 'app.general.pictures'|trans }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if showFBComments %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12 mx-auto">
                    {% include 'includes/comments-facebook.html.twig' %}
                </div>
            </div>
        </div>
    {% endif %}

    {% include 'includes/see-more-posts.html.twig' with {posts: posts} only %}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ name_site }} - Blog
{% endblock %}

{% block body %}
    {% include 'includes/header.html.twig' %}

    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-md-12 mx-auto">
                {% if 0 < posts|length %}
                    {% for post in posts %}
                        <article class="post-preview">
                            <div class="row">
                                <div class="col-md-5">
                                    <a href="{{ path('post_detail', {slug: post.slug}) }}">
                                        {% if post.urlPhoto is not empty %}
                                            <img src="{{ asset(post.urlPhoto)|imagine_filter('600x375') }}"
                                                 class="post-image rounded img-fluid mr-3"
                                                 alt="{{ post.title }}">
                                        {% endif %}
                                    </a>
                                </div>

                                <div class="col-md-7">
                                    <div class="mb-4">
                                        <a href="{{ path('post_detail', {slug: post.slug}) }}">
                                            <h2 class="post-title">{{ post.title }}</h2>
                                            <h3 class="post-subtitle text-limited">{{ post.description }}</h3>
                                        </a>

                                        {% if 0 < post.categories|length %}
                                            <div class="post-categories">
                                                {% for category in post.categories %}
                                                    <a class="badge badge-primary"
                                                       href="{{ path('post_index_category', {category: category.slug}) }}">
                                                        {{ category.name }}
                                                    </a>
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    </div>

                                    <div class="media post-user">
                                        {% if post.user.urlAvatar is not empty %}
                                            <img src="{{ asset(post.user.urlAvatar)|imagine_filter('50x50') }}"
                                                 class="rounded-circle mr-2"
                                                 alt="{{ post.user.fullname }}">
                                        {% endif %}
                                        <div class="media-body">
                                            <h6 class="post-user-name mt-1 mb-1">{{ post.user.fullname }}</h6>

                                            {% include 'includes/published.html.twig' with {published: post.published} only %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                {% else %}
                    Não foi encontrado nenhum artigo
                {% endif %}

                <!-- Pager -->
                <div class="clearfix">
                    {{ knp_pagination_render(posts) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}